### ISSUE TITLE
Try to read the json file only when a functional test was running

### ISSUE THREAD

**Issue by robertoschwald** [rdmueller/grails-filmStrip#33]
Currently unit / integration - only tests fail with this plugin, as the json file is not created (no geb tests run in this case). So either print the json file missing as a warning only, or recognize if a functional test was running at all.

**Comment by robertoschwald** [comment]
Thanks for merging. When do you plan to release a new version? I need it badly, as the plugin currently does not work in our ci env and causes errors, as we are using distributed testing with lots of ci agents to test each steps separaretly (unit, integration and several functional agents)

**Comment by rdmueller** [comment]
it has been a long time since my last release. So I can't guarantee that it will run smooth, but I will try my very best this evening.

**Comment by rdmueller** [comment]
Ha! It worked:
https://grails.org/plugins/search?q=filmstrip

please give it a try!

**Comment by rdmueller** [comment]
close because of no further response
