### ISSUE TITLE
Allow to store the html page in common html report dir

### ISSUE THREAD

**Issue by robertoschwald** [rdmueller/grails-filmStrip#37]
For Ci environments, it must be possible to store the index file in the target/test-reports/html dir, so you can use e.g. Jenkins HTML Report Publisher to publish to the master ci server.

I will send a small PR soon to allow that using Java property option.
This one will also change the version to 0.1.7-SNAPSHOT, as it is not released, yet.

**Comment by rdmueller** [comment]
great. thanx!

To be honest, I haven't published this plugin for a long time and have to figure out again how this works...

If you want to, you could take over the project...

**Comment by robertoschwald** [comment]
Well, there is only one small fix I need to implement, thats the link handling to all.html which is currently broken on Jenkins if using the HTML Publisher Plugin. After that, I think you can publish plugin version 0.1.7, which should be the last one for this old plugin.

**Comment by robertoschwald** [comment]
I will push the all.html fix to a new PR

**Comment by rdmueller** [comment]
sorry that it took so long. Today I will try to publish the new version... let's see if I succeed...

**Comment by rdmueller** [comment]
It worked! Thanx for your PRs!

As I said before - If you would like to, you could take over ownership of this plugin. I would then transfer the repository to your account. Github takes care for redirects from my account to the new location...

**Comment by robertoschwald** [comment]
Thanks Ralf.
As this is for my last Grails 2 project, I don't think its worth it. I'll using a Gradle plugin for the Grails 3.3 projects, soon.

**Comment by rdmueller** [comment]
:-)
